# Very hacky way of only using CodeBuild as a CI/CD Pipeline for AWS
# (so we dont have to pay money for loads of CodePipelines)
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - sam validate
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam deploy --no-confirm-changeset